name: MCPApp
options:
  bundleIdPrefix: com.mcpclient
  deploymentTarget:
    iOS: 16.0
packages:
  MCPiOSClientPackage:
    path: .
targets:
  MCPApp:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: MCPiOSClientApp
        type: group
    info:
      path: MCPiOSClientApp/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mcpclient.ios
        PRODUCT_NAME: MCPApp
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 6.0
        INFOPLIST_FILE: MCPiOSClientApp/Info.plist
        MODULE_NAME: MCPApp
    dependencies:
      - package: MCPiOSClientPackage
        product: MCPiOSClient